2023-04-07 21:47:27,858 INFO    StreamThr :174312 [internal.py:wandb_internal():86] W&B internal server running at pid: 174312, started at: 2023-04-07 21:47:27.858020
2023-04-07 21:47:27,859 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: status
2023-04-07 21:47:27,863 INFO    WriterThread:174312 [datastore.py:open_for_write():85] open: /home/oem/Projects/provably_fl/wandb/run-20230407_214727-1kl3ojsj/run-1kl3ojsj.wandb
2023-04-07 21:47:27,863 DEBUG   SenderThread:174312 [sender.py:send():375] send: header
2023-04-07 21:47:27,874 DEBUG   SenderThread:174312 [sender.py:send():375] send: run
2023-04-07 21:47:28,411 INFO    SenderThread:174312 [dir_watcher.py:__init__():219] watching files in: /home/oem/Projects/provably_fl/wandb/run-20230407_214727-1kl3ojsj/files
2023-04-07 21:47:28,411 INFO    SenderThread:174312 [sender.py:_start_run_threads():1124] run started: 1kl3ojsj with start time 1680871647.859186
2023-04-07 21:47:28,411 DEBUG   SenderThread:174312 [sender.py:send_request():402] send_request: summary_record
2023-04-07 21:47:28,412 INFO    SenderThread:174312 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-04-07 21:47:28,417 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: check_version
2023-04-07 21:47:28,417 DEBUG   SenderThread:174312 [sender.py:send_request():402] send_request: check_version
2023-04-07 21:47:28,469 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: run_start
2023-04-07 21:47:28,475 DEBUG   HandlerThread:174312 [system_info.py:__init__():31] System info init
2023-04-07 21:47:28,475 DEBUG   HandlerThread:174312 [system_info.py:__init__():46] System info init done
2023-04-07 21:47:28,475 INFO    HandlerThread:174312 [system_monitor.py:start():181] Starting system monitor
2023-04-07 21:47:28,476 INFO    SystemMonitor:174312 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-04-07 21:47:28,476 INFO    SystemMonitor:174312 [interfaces.py:start():190] Started cpu monitoring
2023-04-07 21:47:28,476 INFO    HandlerThread:174312 [system_monitor.py:probe():201] Collecting system info
2023-04-07 21:47:28,476 INFO    SystemMonitor:174312 [interfaces.py:start():190] Started disk monitoring
2023-04-07 21:47:28,477 INFO    SystemMonitor:174312 [interfaces.py:start():190] Started gpu monitoring
2023-04-07 21:47:28,478 INFO    SystemMonitor:174312 [interfaces.py:start():190] Started memory monitoring
2023-04-07 21:47:28,478 INFO    SystemMonitor:174312 [interfaces.py:start():190] Started network monitoring
2023-04-07 21:47:28,504 DEBUG   HandlerThread:174312 [system_info.py:probe():195] Probing system
2023-04-07 21:47:28,510 DEBUG   HandlerThread:174312 [system_info.py:_probe_git():180] Probing git
2023-04-07 21:47:28,519 DEBUG   HandlerThread:174312 [system_info.py:_probe_git():188] Probing git done
2023-04-07 21:47:28,519 DEBUG   HandlerThread:174312 [system_info.py:probe():240] Probing system done
2023-04-07 21:47:28,519 DEBUG   HandlerThread:174312 [system_monitor.py:probe():210] {'os': 'Linux-5.15.0-69-generic-x86_64-with-glibc2.17', 'python': '3.8.16', 'heartbeatAt': '2023-04-07T12:47:28.505073', 'startedAt': '2023-04-07T12:47:27.850021', 'docker': None, 'cuda': None, 'args': ('--task', 'cifar100_cnum100_dist1_skew0.8_seed0', '--model', 'cnn', '--algorithm', 'fedprob', '--num_rounds', '500', '--num_epochs', '5', '--learning_rate', '0.01', '--proportion', '0.1', '--batch_size', '10', '--eval_interval', '1', '--log_wandb', '--sigma_certify', '1', '--session_name', 'sigma1'), 'state': 'running', 'program': 'main.py', 'codePath': 'main.py', 'git': {'remote': 'https://github.com/duclong1009/Provably_FL.git', 'commit': 'f3a8e812f390248681165a822addfb8ef8aa93bd'}, 'email': 'duclong10092000@gmail.com', 'root': '/home/oem/Projects/provably_fl', 'host': 'oem-Legion-T730-28ICO', 'username': 'oem', 'executable': '/home/oem/anaconda3/envs/pytorch/bin/python', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3737.5015625, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 4700.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 3600.0, 'min': 800.0, 'max': 5000.0}, {'current': 4700.025, 'min': 800.0, 'max': 5000.0}], 'disk': {'total': 937.3305015563965, 'used': 55.620758056640625}, 'gpu': 'NVIDIA GeForce RTX 2080', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 2080', 'memory_total': 8589934592}], 'memory': {'total': 31.297256469726562}}
2023-04-07 21:47:28,519 INFO    HandlerThread:174312 [system_monitor.py:probe():211] Finished collecting system info
2023-04-07 21:47:28,519 INFO    HandlerThread:174312 [system_monitor.py:probe():214] Publishing system info
2023-04-07 21:47:28,519 DEBUG   HandlerThread:174312 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-04-07 21:47:28,520 DEBUG   HandlerThread:174312 [system_info.py:_save_pip():67] Saving pip packages done
2023-04-07 21:47:28,520 DEBUG   HandlerThread:174312 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-04-07 21:47:29,412 INFO    Thread-12 :174312 [dir_watcher.py:_on_file_created():278] file/dir created: /home/oem/Projects/provably_fl/wandb/run-20230407_214727-1kl3ojsj/files/requirements.txt
2023-04-07 21:47:29,412 INFO    Thread-12 :174312 [dir_watcher.py:_on_file_created():278] file/dir created: /home/oem/Projects/provably_fl/wandb/run-20230407_214727-1kl3ojsj/files/conda-environment.yaml
2023-04-07 21:47:29,413 INFO    Thread-12 :174312 [dir_watcher.py:_on_file_created():278] file/dir created: /home/oem/Projects/provably_fl/wandb/run-20230407_214727-1kl3ojsj/files/wandb-summary.json
2023-04-07 21:47:31,053 DEBUG   HandlerThread:174312 [system_info.py:_save_conda():86] Saving conda packages done
2023-04-07 21:47:31,053 INFO    HandlerThread:174312 [system_monitor.py:probe():216] Finished publishing system info
2023-04-07 21:47:31,056 DEBUG   SenderThread:174312 [sender.py:send():375] send: files
2023-04-07 21:47:31,056 INFO    SenderThread:174312 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-04-07 21:47:31,061 DEBUG   SenderThread:174312 [sender.py:send():375] send: telemetry
2023-04-07 21:47:31,094 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: stop_status
2023-04-07 21:47:31,094 DEBUG   SenderThread:174312 [sender.py:send_request():402] send_request: stop_status
2023-04-07 21:47:31,272 DEBUG   SenderThread:174312 [sender.py:send():375] send: telemetry
2023-04-07 21:47:31,411 INFO    Thread-12 :174312 [dir_watcher.py:_on_file_modified():295] file/dir modified: /home/oem/Projects/provably_fl/wandb/run-20230407_214727-1kl3ojsj/files/conda-environment.yaml
2023-04-07 21:47:31,411 INFO    Thread-12 :174312 [dir_watcher.py:_on_file_created():278] file/dir created: /home/oem/Projects/provably_fl/wandb/run-20230407_214727-1kl3ojsj/files/wandb-metadata.json
2023-04-07 21:47:31,411 INFO    Thread-12 :174312 [dir_watcher.py:_on_file_created():278] file/dir created: /home/oem/Projects/provably_fl/wandb/run-20230407_214727-1kl3ojsj/files/output.log
2023-04-07 21:47:31,603 INFO    wandb-upload_0:174312 [upload_job.py:push():137] Uploaded file /tmp/tmplgdjqzffwandb/fz0llgmq-wandb-metadata.json
2023-04-07 21:47:33,272 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: status_report
2023-04-07 21:47:33,412 INFO    Thread-12 :174312 [dir_watcher.py:_on_file_modified():295] file/dir modified: /home/oem/Projects/provably_fl/wandb/run-20230407_214727-1kl3ojsj/files/output.log
2023-04-07 21:47:38,273 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: status_report
2023-04-07 21:47:43,274 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: status_report
2023-04-07 21:47:48,274 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: status_report
2023-04-07 21:47:53,275 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: status_report
2023-04-07 21:47:58,279 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: status_report
2023-04-07 21:47:58,449 ERROR   SenderThread:174312 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-04-07 21:47:58,449 ERROR   SenderThread:174312 [internal_api.py:execute():289] {"errors":[{"message":"run aiotlab/Provably_Fl/1kl3ojsj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-07 21:47:59,677 ERROR   SenderThread:174312 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-04-07 21:47:59,677 ERROR   SenderThread:174312 [internal_api.py:execute():289] {"errors":[{"message":"run aiotlab/Provably_Fl/1kl3ojsj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-07 21:48:02,332 ERROR   SenderThread:174312 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-04-07 21:48:02,332 ERROR   SenderThread:174312 [internal_api.py:execute():289] {"errors":[{"message":"run aiotlab/Provably_Fl/1kl3ojsj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-07 21:48:02,332 INFO    SenderThread:174312 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-04-07 21:48:07,279 ERROR   SenderThread:174312 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-04-07 21:48:07,279 ERROR   SenderThread:174312 [internal_api.py:execute():289] {"errors":[{"message":"run aiotlab/Provably_Fl/1kl3ojsj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-07 21:48:13,282 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: stop_status
2023-04-07 21:48:15,724 ERROR   SenderThread:174312 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-04-07 21:48:15,724 ERROR   SenderThread:174312 [internal_api.py:execute():289] {"errors":[{"message":"run aiotlab/Provably_Fl/1kl3ojsj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-07 21:48:19,224 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:48:24,428 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:48:28,478 DEBUG   SystemMonitor:174312 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-04-07 21:48:30,108 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:48:32,902 ERROR   SenderThread:174312 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-04-07 21:48:32,902 ERROR   SenderThread:174312 [internal_api.py:execute():289] {"errors":[{"message":"run aiotlab/Provably_Fl/1kl3ojsj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-07 21:48:35,410 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:48:40,411 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:48:41,066 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:48:44,683 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:48:45,412 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:48:48,331 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:48:50,413 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:48:51,984 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:48:55,413 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:48:55,585 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:48:59,229 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:00,414 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:02,948 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:05,415 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:06,658 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:07,046 ERROR   SenderThread:174312 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-04-07 21:49:07,046 ERROR   SenderThread:174312 [internal_api.py:execute():289] {"errors":[{"message":"run aiotlab/Provably_Fl/1kl3ojsj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-07 21:49:10,282 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:10,415 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:13,920 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:15,416 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:17,528 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:20,417 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:21,156 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:24,812 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:25,417 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:28,510 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:30,418 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:32,285 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:35,419 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:36,097 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:39,770 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:40,420 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:43,501 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:45,421 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:47,145 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:50,421 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:50,779 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:54,463 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:49:55,422 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:49:58,128 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:50:00,423 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:50:01,706 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:50:05,265 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:50:05,423 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:50:08,932 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:50:10,424 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:50:12,879 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:50:15,425 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: keepalive
2023-04-07 21:50:16,744 DEBUG   HandlerThread:174312 [handler.py:handle_request():144] handle_request: partial_history
2023-04-07 21:50:17,749 ERROR   SenderThread:174312 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-04-07 21:50:17,749 ERROR   SenderThread:174312 [internal_api.py:execute():289] {"errors":[{"message":"run aiotlab/Provably_Fl/1kl3ojsj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-07 21:50:18,744 INFO    HandlerThread:174312 [handler.py:finish():845] shutting down handler
2023-04-07 21:50:18,745 INFO    HandlerThread:174312 [system_monitor.py:finish():190] Stopping system monitor
2023-04-07 21:50:18,745 DEBUG   SystemMonitor:174312 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-04-07 21:50:18,745 DEBUG   SystemMonitor:174312 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-04-07 21:50:18,745 INFO    WriterThread:174312 [datastore.py:close():298] close: /home/oem/Projects/provably_fl/wandb/run-20230407_214727-1kl3ojsj/run-1kl3ojsj.wandb
2023-04-07 21:50:18,746 INFO    HandlerThread:174312 [interfaces.py:finish():202] Joined cpu monitor
2023-04-07 21:50:18,746 INFO    HandlerThread:174312 [interfaces.py:finish():202] Joined disk monitor
2023-04-07 21:50:18,783 INFO    HandlerThread:174312 [interfaces.py:finish():202] Joined gpu monitor
2023-04-07 21:50:18,783 INFO    HandlerThread:174312 [interfaces.py:finish():202] Joined memory monitor
2023-04-07 21:50:18,783 INFO    HandlerThread:174312 [interfaces.py:finish():202] Joined network monitor
2023-04-07 21:50:18,783 ERROR   StreamThr :174312 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1690, in upsert_run
    response = self.gql(
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 257, in gql
    ret = self._retry_gql(
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 551, in debounce
    self._maybe_update_config(always=final)
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 528, in _maybe_update_config
    self._debounce_config()
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 557, in _debounce_config
    self._api.upsert_run(
  File "/home/oem/anaconda3/envs/pytorch/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run aiotlab/Provably_Fl/1kl3ojsj was previously created and deleted; try a new run name (Error 409: Conflict)
